import pandas as pd
import numpy as np
import config

def generate_signals(df):
    """
    Moving Average Crossover Strategy.
    This is a classic trend-following strategy. It buys when a short-term moving average
    crosses above a long-term moving average (Golden Cross), and sells when it crosses below (Death Cross).
    """
    # --- Strategy Parameters ---
    # Fetch parameters from the main config file, providing defaults if they don't exist
    slow_period = getattr(config, 'STRATEGY_SLOW_PERIOD', 200) # Long-term trend (e.g., 200-period)
    fast_period = getattr(config, 'STRATEGY_FAST_PERIOD', 50)  # Short-term trend (e.g., 50-period)
    
    # Ensure we have enough data to calculate the slow moving average
    if len(df) < slow_period:
        df['signal'] = 0
        df['dynamic_sl_points'] = 0
        return df

    # --- Indicator Calculation ---
    # SMA (Simple Moving Average) calculates the average price over a specific number of periods
    df['SMA_Fast'] = df['close'].rolling(window=fast_period).mean() # Fast SMA responds quickly to price changes
    df['SMA_Slow'] = df['close'].rolling(window=slow_period).mean() # Slow SMA represents the broader trend

    # --- Setup for Signal Generation ---
    # Shift values by 1 period to avoid look-ahead bias. 
    # We want to detect the exact moment a crossover happens between the previous candle and the current one.
    df['SMA_Fast_prev'] = df['SMA_Fast'].shift(1)
    df['SMA_Slow_prev'] = df['SMA_Slow'].shift(1)

    # --- Trading Logic ---
    # Buy Signal (Golden Cross):
    # Fast SMA was below or equal to Slow SMA previously, but is now strictly above it.
    buy_condition = (df['SMA_Fast_prev'] <= df['SMA_Slow_prev']) & (df['SMA_Fast'] > df['SMA_Slow'])
    
    # Sell Signal (Death Cross):
    # Fast SMA was above or equal to Slow SMA previously, but is now strictly below it.
    sell_condition = (df['SMA_Fast_prev'] >= df['SMA_Slow_prev']) & (df['SMA_Fast'] < df['SMA_Slow'])

    # --- Assign Signals ---
    # 0 = No Action, 1 = Buy, -1 = Sell
    df['signal'] = 0
    df.loc[buy_condition, 'signal'] = 1
    df.loc[sell_condition, 'signal'] = -1
    
    # Set dynamic stop loss to 0, which tells the bot to fall back to the default config.STOP_LOSS_POINTS
    df['dynamic_sl_points'] = 0  
    
    return df

def check_for_signals(df):
    """
    Adapter for LIVE mode to fetch the most recent signal generated by the strategy.
    """
    df_signals = generate_signals(df)
    last_row = df_signals.iloc[-1] # Grabs the last closed candle
    
    # Output a clear message for the user when a trade condition is met
    if last_row['signal'] == 1:
        print("Strategy Engine: Bullish Crossover Detected (BUY SIGNAL)")
    elif last_row['signal'] == -1:
        print("Strategy Engine: Bearish Crossover Detected (SELL SIGNAL)")
        
    return last_row['signal'], last_row['dynamic_sl_points']