import time
import sys
import MetaTrader5 as mt5

# Import global configurations
import config

# Import structural modules
from data.ingestion import init_connection, get_historical_bars, get_latest_tick, shutdown_connection
from execution.risk import calculate_position_size
from execution.orders import get_open_positions, execute_trade, close_position
from utils.time_sync import is_safe_to_trade, get_current_melbourne_time

def initialize_system():
    """
    Handles the secure login sequence to the MetaTrader 5 terminal
    using the credentials routed via config.py.
    """
    print("=" * 50)
    print("INITIALIZING ALGORITHMIC TRADING SYSTEM")
    print("=" * 50)
    
    # Initialize connection to MT5
    if not init_connection():
        print("CRITICAL: Could not connect to MT5 Terminal. Exiting system.")
        sys.exit(1)
        
    # Log into the specific broker account
    login_success = mt5.login(
        login=config.MT5_LOGIN,
        password=config.MT5_PASSWORD,
        server=config.MT5_SERVER
    )
    
    if not login_success:
        print(f"CRITICAL: Broker login failed. MT5 Error: {mt5.last_error()}")
        shutdown_connection()
        sys.exit(1)
        
    print(f"Logged into Account: {config.MT5_LOGIN} ({config.ENVIRONMENT} Mode)")
    print(f"Target Asset: {config.SYMBOL}")
    print("System status: ONLINE & RUNNING\n")

def run_trading_loop():
    """
    The core execution engine that keeps the bot polling the market,
    evaluating rules, managing risk, and processing exits/entries.
    """
    # Dynamic strategy import fallback to ensure compilation
    try:
        from strategies.moving_avg import check_for_signals
    except ImportError:
        print("Strategy file not found. Using an inline temporary strategy placeholder.")
        def check_for_signals(df):
            # Baseline dummy strategy contract placeholder: (signal, stop_loss_points)
            return 0, 0

    while True:
        try:
            current_time = get_current_melbourne_time()
            print(f"[{current_time.strftime('%Y-%m-%d %H:%M:%S')} AEST] Scanning market...")

            # 1. Operational Safety Gate (Timezone & Session Filter)
            if not is_safe_to_trade():
                print("Market Status: CLOSED or LOW LIQUIDITY WINDOW. Pausing execution.")
                time.sleep(60)
                continue

            # 2. Synchronize Market Data
            # Fetch an extra 10 bars above slow period to ensure indicators stabilize
            required_bars = config.STRATEGY_SLOW_PERIOD + 10 if hasattr(config, 'STRATEGY_SLOW_PERIOD') else 100
            df = get_historical_bars(config.SYMBOL, config.TIMEFRAME, required_bars)
            
            if df is None or df.empty:
                print("Warning: Data stream interrupted. Retrying next cycle.")
                time.sleep(10)
                continue

            # 3. Position Inventory Management (Exits First)
            # Retrieve open positions generated by this specific bot framework
            open_trades = get_open_positions(config.SYMBOL)
            
            # Extract strategy calculations
            signal, strategy_sl_points = check_for_signals(df)
            
            has_long = any(t.type == mt5.POSITION_TYPE_BUY for t in open_trades)
            has_short = any(t.type == mt5.POSITION_TYPE_SELL for t in open_trades)

            # Check for structural exit conditions (Opposite signal logic)
            for trade in open_trades:
                if trade.type == mt5.POSITION_TYPE_BUY and signal == -1:
                    print(f"Exit Signal Detected! Closing Long Position: {trade.ticket}")
                    close_position(trade.ticket)
                    has_long = False
                    
                elif trade.type == mt5.POSITION_TYPE_SELL and signal == 1:
                    print(f"Exit Signal Detected! Closing Short Position: {trade.ticket}")
                    close_position(trade.ticket)
                    has_short = False

            # 4. Entry Order Execution Logic
            if signal != 0:
                # Fetch live order book constraints
                tick = get_latest_tick(config.SYMBOL)
                account_info = mt5.account_info()
                
                if tick and account_info:
                    # Resolve trade-specific parameters
                    sl_points = strategy_sl_points if strategy_sl_points > 0 else config.STOP_LOSS_POINTS
                    
                    # Calculate safe position sizing aligned to your account risk rules
                    calculated_lots = calculate_position_size(
                        symbol=config.SYMBOL,
                        account_balance=account_info.balance,
                        risk_percentage=config.RISK_PERCENT,
                        stop_loss_points=sl_points
                    )
                    
                    # Execute BUY order if clear of active long contracts
                    if signal == 1 and not has_long:
                        print(f"Execution Strategy: Triggering LONG Trade. Lots: {calculated_lots}")
                        sl_price = tick['ask'] - (sl_points * mt5.symbol_info(config.SYMBOL).point)
                        tp_price = tick['ask'] + (sl_points * 2 * mt5.symbol_info(config.SYMBOL).point) # 1:2 RVR default
                        
                        execute_trade(
                            symbol=config.SYMBOL,
                            order_type=mt5.ORDER_TYPE_BUY,
                            lot_size=calculated_lots,
                            price=tick['ask'],
                            sl=sl_price,
                            tp=tp_price,
                            magic_number=config.MAGIC_NUMBER
                        )
                    
                    # Execute SELL order if clear of active short contracts
                    elif signal == -1 and not has_short:
                        print(f"Execution Strategy: Triggering SHORT Trade. Lots: {calculated_lots}")
                        sl_price = tick['bid'] + (sl_points * mt5.symbol_info(config.SYMBOL).point)
                        tp_price = tick['bid'] - (sl_points * 2 * mt5.symbol_info(config.SYMBOL).point) # 1:2 RVR default
                        
                        execute_trade(
                            symbol=config.SYMBOL,
                            order_type=mt5.ORDER_TYPE_SELL,
                            lot_size=calculated_lots,
                            price=tick['bid'],
                            sl=sl_price,
                            tp=tp_price,
                            magic_number=config.MAGIC_NUMBER
                        )
            
            # Throttling frequency matching execution profile (e.g., standard 10-second tick)
            time.sleep(10)

        except KeyboardInterrupt:
            print("\nShutdown command acknowledged by operator.")
            break
        except Exception as e:
            print(f"Unexpected Runtime System Exception Error: {e}")
            time.sleep(15)

if __name__ == "__main__":
    # Fire up the stack connection
    initialize_system()
    
    # Enter perpetual loop tracking window
    run_trading_loop()
    
    # Clean termination sequence
    shutdown_connection()
    print("=" * 50)
    print("SYSTEM DEACTIVATED - GRACEFUL SHUTDOWN COMPLETE")
    print("=" * 50)